CMakeLists.txt
include/sparrow/sparrow_version.hpp
test/main.cpp

This is both to avoid using the preprocessor in C++ in general, and to prepare for future usage of the library as a C++ module.

Use constexpr constants instead of defines.

---

include/sparrow/iterator.hpp

I replaced `WIN32` by `_WIN32` because the first one is defined by headers from window's sdk, not by the compiler, while the second one is defined by the compiler.
Details of the access issue:
https://developercommunity.visualstudio.com/t/Private-member-inaccessible-when-used-in/10448363?q=friend+private

Fixes and clarify workaround of access issue with friend functions with msvc

---

CMakeLists.txt
include/sparrow/buffer.hpp
include/sparrow/dynamic_bitset.hpp
test/CMakeLists.txt
test/test_dynamic_bitset.cpp
test/test_iterator.cpp

based on #16 , partially replaces #13 
You can ignore the first 3 commits for the review (they will disappear when #16 is merged and this one is rebased).

Dynamic bitset

---

CMakeLists.txt

Requiring 3.28 is constraining for some build systems like vcpkg's which [currently uses CMake 3.27.1](https://github.com/microsoft/vcpkg/blame/7f9f0e44db287e8e67c0e888141bfa200ab45121/scripts/vcpkgTools.xml#L34).

build: Require CMake 3.27

---

include/sparrow/array_data.hpp
include/sparrow/layout.hpp
test/CMakeLists.txt
test/test_layout.cpp

Comes after #13.
Partially addresses #14.

Primitive layout

---

.github/workflows/linux.yml
.github/workflows/osx.yml
.github/workflows/windows.yml
.gitignore
CMakeLists.txt
test/CMakeLists.txt

- using `ctest` to run the tests, which means we dont have to change the command executing tests every time we want to add a test executable or configuration;
- specifies `Debug` and `Release` configurations to be explicitly built and tested, to avoid issues because of CMake's inconsistency in the output of generators (some build-systems allow multiple configurations, so that removes any ambiguity) - also for installing;
- builds with both Ninja and VS on Windows, with msvc, mingw and clang;
- git-ignore some poentially generated directories
- fixed some ci runs names

Various Minor CI fixes

---

include/sparrow/buffer.hpp
include/sparrow/fixed_size_layout.hpp
include/sparrow/iterator.hpp

The current `buffer_iterator` and `fixed_size_layout_value_iterator` are very similar, they adapt a pointer to make it an iterator. More classes to come will have to do the same. This PR captures the common implementation in the `pointer_iterator` class, to reduce code duplication.

Implemented pointer_iterator

---

include/sparrow/iterator.hpp
test/test_iterator.cpp

This will make it easier to create other iterator adaptors.

Added iterator_adaptor, refactored pointer_iterator

---

.clang-format
.github/workflows/analysis.yaml
.github/workflows/linux.yml
CMakeLists.txt
cmake/clang-format.cmake
include/sparrow/array_data.hpp
include/sparrow/buffer.hpp
include/sparrow/data_traits.hpp
include/sparrow/data_type.hpp
include/sparrow/details/3rdparty/.clang-format
include/sparrow/dictionary_encoded_layout.hpp
include/sparrow/dynamic_bitset.hpp
include/sparrow/fixed_size_layout.hpp
include/sparrow/iterator.hpp
include/sparrow/mp_utils.hpp
include/sparrow/sparrow_version.hpp
include/sparrow/variable_size_binary_layout.hpp
test/CMakeLists.txt
test/main.cpp
test/test_array_data.cpp
test/test_buffer.cpp
test/test_dictionary_encoded_layout.cpp
test/test_dynamic_bitset.cpp
test/test_fixed_size_layout.cpp
test/test_iterator.cpp
test/test_mpl.cpp
test/test_traits.cpp
test/test_variable_size_binary_layout.cpp

Fix #42
There is no warning in the checks as we only check modified files.
You can test the rules with https://clang-format-configurator.site/
There are 2 cmake targets: a dry run and an auto fix which run over all the files.

Add clang format

---

CMakeLists.txt
include/sparrow/array_data.hpp
include/sparrow/memory.hpp
test/CMakeLists.txt
test/test_dictionary_encoded_layout.cpp
test/test_memory.cpp

Fix #57 
Implement value_ptr class

Add value_ptr

---

CMakeLists.txt
include/sparrow/allocator.hpp
include/sparrow/buffer.hpp
include/sparrow/buffer_view.hpp
include/sparrow/dynamic_bitset.hpp
test/test_allocator.cpp
test/test_buffer.cpp

Refactored buffer and buffer_view

---

CMakeLists.txt
include/sparrow/array_data.hpp
include/sparrow/buffer.hpp
include/sparrow/contracts.hpp
include/sparrow/dictionary_encoded_layout.hpp
include/sparrow/dynamic_bitset.hpp
include/sparrow/fixed_size_layout.hpp
include/sparrow/memory.hpp
include/sparrow/variable_size_binary_layout.hpp
test/test_array_data.cpp
test/test_variable_size_binary_layout.cpp

This provides macros (extracted from my library NoContracts) for contract assertions checks, named with SPARROW_ so that control over enabling these assertions is let to the user.
The checks are enabled by default and all C `assert(...)` calls have been replaced.

Contracts header with assertion macros specific to Sparrow

---

.github/workflows/osx.yml
include/sparrow/algorithm.hpp
include/sparrow/config.hpp

Even-though conda-forge's toolchain allows for using clang++ 18, libc++ 16 is the latest version available (see https://github.com/conda-forge/libcxx-feedstock/pull/131).
The `std::lexicographical_compare_three_way` has only been implemented in libc++ 17, so we use the vendored implementation when libc++ < 17 is used.

Support clang++ from conda-forge

---

.github/workflows/linux.yml
include/sparrow/iterator.hpp

GCC / stdlibc++ 13 is relatively recent for most toolchains.
Let's also support GCC / stdlibc++ 12.

ci: Test GCC 12 on Linux

---

.github/workflows/linux.yml
.github/workflows/osx.yml

[Ubuntu 22.04 images have been released yesterday](https://github.com/xtensor-stack/sparrow/actions/runs/9113436623/job/25054935536#step:4:11).
[`libstdc++-13-dev` cannot be resolved on this platform](https://github.com/xtensor-stack/sparrow/actions/runs/9113436623/job/25054935536#step:4:11).

ci: Use libstdc++-12 after the upgrade to Ubuntu 22.04

---

.clang-format
include/sparrow/allocator.hpp
include/sparrow/array_data.hpp
include/sparrow/buffer.hpp
include/sparrow/buffer_view.hpp
include/sparrow/contracts.hpp
include/sparrow/data_type.hpp
include/sparrow/dictionary_encoded_layout.hpp
include/sparrow/dynamic_bitset.hpp
include/sparrow/fixed_size_layout.hpp
include/sparrow/memory.hpp
include/sparrow/mp_utils.hpp
include/sparrow/typed_array.hpp
include/sparrow/variable_size_binary_layout.hpp
test/CMakeLists.txt
test/array_data_creation.hpp
test/test_allocator.cpp
test/test_dictionary_encoded_layout.cpp
test/test_dynamic_bitset.cpp
test/test_fixed_size_layout.cpp
test/test_iterator.cpp
test/test_typed_array.cpp
test/test_variable_size_binary_layout.cpp

Add warnings options

---

.github/workflows/linux.yml
.github/workflows/osx.yml
.github/workflows/windows.yml
CMakeLists.txt
environment-dev.yml
include/sparrow/buffer.hpp
include/sparrow/data_traits.hpp
include/sparrow/data_type.hpp
test/CMakeLists.txt
test/array_data_creation.cpp
test/array_data_creation.hpp
test/test_typed_array_timestamp.cpp

Support for timestamps

---

include/sparrow/data_type.hpp

- defined SPARROW_STD_FIXED_FLOAT_SUPPORT which if set means we do have access to the standard fixed float support - otherwise not
- detected when the support for fixed floats does not exist more correctly
-  ignore warnings from deprecated standard library usage in float16_t

workaround fixed float build issues (detected through build2 packaging)

---

CMakeLists.txt
include/sparrow/c_interface.hpp
test/CMakeLists.txt
test/test_c_data_interface.cpp

Arrow c data interface

---

.github/workflows/publish_test_report.yml

This PR is to unlock the branch the improve the reporting of the UT reports as the workflow which depends on another workflow must be on the default branch.

Add publish test report github action

---

CMakeLists.txt
include/sparrow/array_data_factory.hpp
include/sparrow/data_traits.hpp
include/sparrow/data_type.hpp
include/sparrow/null_layout.hpp
test/CMakeLists.txt
test/test_null_layout.cpp

Added null_type and implemented null_layout

---

include/sparrow/typed_array.hpp

I see the same issue as mentioned in #108 
This crude workaround/hack allows me to compile on mac with clang

workaround for clang/apple/libc++

---

include/sparrow/data_traits.hpp
include/sparrow/dictionary_encoded_layout.hpp
include/sparrow/mp_utils.hpp
include/sparrow/variable_size_binary_layout.hpp
test/test_array_data_concepts.cpp
test/test_array_data_factory.cpp
test/test_dictionary_encoded_layout.cpp
test/test_typed_array.cpp
test/test_variable_size_binary_layout.cpp

`variable_size_binary_layout` inner ref

---

CMakeLists.txt

This also fixes VS not being able to see the sparrow target because it had not associated files.

cmake fix: sparrow target had no sources

---

examples/CMakeLists.txt
examples/typed_array_high_level.cpp
include/sparrow/array/array_data.hpp
include/sparrow/array/array_data_concepts.hpp
include/sparrow/array/array_data_factory.hpp
include/sparrow/array/external_array_data.hpp
include/sparrow/array/typed_array.hpp
include/sparrow/layout/fixed_size_layout.hpp
include/sparrow/layout/variable_size_binary_layout.hpp
test/test_array_data.cpp
test/test_typed_array.cpp

* use pre-existing factory functions
* use values for bitmaps instead of const reference
* remove requirement for const_range (does not work for std::vector<bool> because our concept check for const_ranges is not working for std::vector<bool> )
* added `is_mutable` to array_data / external_array_data
The constructor from ranges for ranges of nullables will be added in a followup PR

factory function refactor

---

examples/typed_array_high_level.cpp
include/sparrow/array/array_data_factory.hpp
include/sparrow/array/typed_array.hpp
include/sparrow/utils/mp_utils.hpp
include/sparrow/utils/nullable.hpp
test/test_typed_array.cpp
test/test_variable_size_binary_layout.cpp

* use a range of bools instead of a bitmap in the factory functions:
* this allows to split a vector<nullable<T>> into two ranges, the values and the bitmaps
* this can then be passed to pre-existing factory functions
* note that this changes how the length of missing values is accounted for in the dynamic layout (see below)   
This changes some behavior:
```
values = ["fo", "bar", "fubar"]
bitmap  = [1,0,1]  
```
used to account space  for "bar" in the offsets.
This PR changes this st. we will **not take** the length of "bar" into account since its a missing value (ie the effective length will be 0)
Why? This is the only consistent way of doing it:
Consider a range of nullables:
```C++
std::vector<nullable<std::string>> {
nullable("fo"), nullval, nullval("fubar")
}
```
Here it's clear …

Nullable range constructor

---

include/sparrow/config/sparrow_version.hpp

Makes sure it's clear that `main` is now work on v0.0.4

Begin work on v0.0.4

---

include/sparrow/buffer/buffer_adaptor.hpp
include/sparrow/utils/mp_utils.hpp
test/test_buffer_adaptor.cpp
test/test_mpl.cpp

buffer_adaptor can now takes as input a const reference to a container. In that case all the const methods are disabled.

Buffer adaptor with immutable input

---

include/sparrow/array/data_traits.hpp
include/sparrow/array/data_type.hpp
test/test_traits.cpp

Rewrite the `arrow_traits` specializations for standard integral and floating-point types support.
The main goal is to fix #162 by providing generic traits that will adapt to both situations:
- when `double` and `float64_t` are aliases (1 traits specialization generated for the real type)
- when they are not aliases but distinct types (2 traits spetialization generated, one for each distinct type)
Although the issue was originally spotted with `double` usage, I generalized to all floating-point and integer types as the issue might arise with these types too. It also reduces the code a lot.

Generic traits for standard base types (partial fix #162)

---

include/sparrow_v01/utils/memory.hpp
test_v01/test_memory.cpp

Fixes #195 
This is a very basic implementation that can be improved in the future:
- add a deleter template parameter (similar to `std::unique_ptr`)
- add a cloner template parameter with a default value. This sould allow to merge the `cloning_ptr` and the `value_ptr` classes.
Notice that this adds some complexity to the constructors that I did not want to handle at the moment. I'll open an issue when this is merged.

Implemented cloning_ptr

---

CMakeLists.txt
conanfile.py
include/sparrow/array/data_type.hpp
include/sparrow/arrow_array_schema_proxy.hpp
include/sparrow/arrow_interface/arrow_array_schema_proxy_utils.hpp
include/sparrow/arrow_interface/arrow_flag_utils.hpp
include/sparrow/arrow_interface/arrow_schema.hpp
include/sparrow/arrow_interface/arrow_schema/private_data.hpp
include/sparrow/arrow_interface/arrow_schema/smart_pointers.hpp
include/sparrow/buffer/allocator.hpp
include/sparrow/buffer/buffer_view.hpp
include/sparrow/c_interface.hpp
include/sparrow/utils/variant_visitor.hpp
test/CMakeLists.txt
test/external_array_data_creation.hpp
test/test_arrow_array_schema_proxy.cpp

This first PR is for "read only". You can't reallocate buffers, change the size, etc ...

Arrow array schema proxy

---

.github/workflows/linux.yml
.github/workflows/osx.yml
.github/workflows/windows.yml
CMakeLists.txt
include/sparrow/config/config.hpp
include/sparrow_v01/dummy.hpp
src_v01/dummy.cpp

Let's handle static build and versionning when the refactoring is done. For now, this handles symbol visibility (defaulted to hidden).

Minimal setup for building a shared library

---

include/sparrow/layout/list_layout/list_value.hpp

Ideally I would like to replace the implementation of `operator==` with:
- `return this->size() == rhs.size() && std::ranges::equal(*this, rhs);`: this requires the definition of common reference between unrelated nullable types
- `return this->size() == rhs.size() && std::equal(this->begin(), this->end(), rhs.begin());`: this fails on OSX because it requires the definition of some pointer traits / common traits with nullable
So let's keep it as is for now.

Removed subrange implementation

---

test/test_arrow_array_schema_proxy.cpp

In these tests the children objects are associated to their parents through reference semantics but are created after their parents on the stack. This means that when the stack unrolls, the children are created first, then the destructor of their parent, which still points to their memory on the stack, tries to access the children to release their data, which leads to ASAN reporting a [`stack-user-after-scope`](https://learn.microsoft.com/en-us/cpp/sanitizers/error-stack-use-after-scope?view=msvc-170) error.
Fixed by making sure the lifetime of the children accessed through reference-semantics is always bigger than their parent's lifetime.

Fixes ASAN reports: stack objects destroyed before use

---

CMakeLists.txt
include/sparrow/array_factory.hpp
include/sparrow/layout/array_base.hpp
include/sparrow/layout/array_wrapper.hpp
include/sparrow/layout/dictionary_encoded_array.hpp
include/sparrow/layout/dispatch.hpp
include/sparrow/layout/list_layout/list_array.hpp
include/sparrow/layout/list_layout/list_value.hpp
include/sparrow/layout/null_array.hpp
include/sparrow/layout/primitive_array.hpp
include/sparrow/layout/struct_layout/struct_array.hpp
include/sparrow/layout/struct_layout/struct_value.hpp
include/sparrow/layout/variable_size_binary_array.hpp
include/sparrow/utils/iterator.hpp
include/sparrow/utils/memory.hpp
include/sparrow/utils/nullable.hpp
src/array_factory.cpp
src/list_value.cpp
src/struct_value.cpp
test/CMakeLists.txt
test/test_array_wrapper.cpp
test/test_arrow_array.cpp
test/test_dispatch.cpp
test/test_list_array.cpp
test/test_list_value.cpp
test/test_memory.cpp

This makes the type erasure independent from the array classes. The array facade will follow in a dedicated PR.

Type erasure

---

test/arrow_array_schema_creation.hpp
test/external_array_data_creation.cpp
test/external_array_data_creation.hpp

The next step will be to move all the fill_schema_and_array methods into the different layouts (as factory functions) and remove them from external_array_data_creation.hpp/.cpp. Only the fill_extenral_schema_and_array function (and it dependencies) should remain in these files.

Cleanup of external_array_data_creation

---

CMakeLists.txt
include/sparrow/array.hpp
include/sparrow/array_api.hpp
test/test_array.cpp

Fixes #197.
This is based on #252 to avoid conflicts, therefors you can ignore the first commit when reviewing this PR. Splitting the array header is required because the implementation of `array::visit` includes `layout/dispatch.hpp`, which includes all the layouts, and some of them depends on `array`.

Array dispatch

---

include/sparrow/layout/array_access.hpp
include/sparrow/layout/array_base.hpp
include/sparrow/layout/array_wrapper.hpp
include/sparrow/layout/dictionary_encoded_array.hpp
include/sparrow/layout/mutable_array_base.hpp
include/sparrow/layout/null_array.hpp
include/sparrow/layout/primitive_array.hpp
include/sparrow/layout/run_end_encoded_layout/run_end_encoded_array.hpp
include/sparrow/layout/union_array.hpp
include/sparrow/layout/variable_size_binary_array.hpp
include/sparrow/utils/crtp_base.hpp
test/test_primitive_array.cpp

- Removed using declaration importing CRTP base class methods to avoid typing `this->`
- USed array_access for every access to the layouts proxy
- Removed useless friendships
- Moved almost of methods of primitive_arrya to the private section
- Made primitive_array constructor explicit except for the one accepting an `initializer_list`

Layout hierarchy cleanup

---

include/sparrow/layout/dictionary_encoded_array.hpp
include/sparrow/layout/layout_utils.hpp

See: https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4459?view=msvc-170 For some reason this warning treated as error is not stopping the CI for Windows/msvc build. I didn't find the reason, but I needed this change to be able to build `main` locally.
This solution is the simplest but another more general solution would be to move sparrow concepts in their own namespace (`concepts::layout` for example).
Personally I dont mind local shadowing of names so deactivating this warning would work for me too.

Workaround MSVC warning treated as error (C4459)

---

CMakeLists.txt
include/sparrow/config/sparrow_version.hpp

Instead of custom variable names, use the standard CMAKE_PROJECT_VERSION, PROJECT_VERSION_MAJOR etc.
Use them to properly set SOVERSION.

Normalize project versioning and soname

---

README.md

Fix link for OSX GitHub actions on README

---

test/test_builder.cpp
test/test_builder_dict_encoded.cpp
test/test_builder_run_end_encoded.cpp
test/test_dictionary_encoded_array.cpp
test/test_utils.hpp

* added roundtrip test to generic testing: go to detyped array and than back to a typed one via visiting
* use generic tests for all builder-created arrays

more tests

---

.github/workflows/qemu.yaml
CMakeLists.txt
include/sparrow/arrow_array_schema_proxy.hpp
include/sparrow/buffer/dynamic_bitset/dynamic_bitset.hpp
include/sparrow/buffer/dynamic_bitset/dynamic_bitset_base.hpp
include/sparrow/layout/array_base.hpp
include/sparrow/layout/decimal_array.hpp
include/sparrow/layout/dictionary_encoded_array.hpp
include/sparrow/layout/list_layout/list_array.hpp
include/sparrow/layout/null_array.hpp
include/sparrow/layout/primitive_array.hpp
include/sparrow/layout/run_end_encoded_layout/run_end_encoded_array.hpp
include/sparrow/layout/struct_layout/struct_array.hpp
include/sparrow/layout/union_array.hpp
include/sparrow/layout/variable_size_binary_layout/variable_size_binary_array.hpp
include/sparrow/layout/variable_size_binary_view_array.hpp
include/sparrow/utils/large_int.hpp
src/arrow_array_schema_proxy.cpp
src/run_encoded_array.cpp
test/test_decimal_array.cpp
test/test_dictionary_encoded_array.cpp
test/test_dynamic_bitset.cpp
test/test_null_array.cpp
test/test_primitive_array.cpp
test/test_string_array.cpp
test/test_variable_size_binary_view_array.cpp

Sorry there is a lot of formatting, please ignore the whitespaces in the viewer's settings

Add name metadata convenient constructors

---

README.md

This seems to have been carried over from the previous snippet.

Fix snippet in Readme

---

include/sparrow/details/3rdparty/float16_t.hpp

Hi, 
I shall be trying to address the emscripten build of sparrow through a series of 2-3 PRs. We should then be able to use it directly through xeus-cpp-lite. Once done, I shall also add a CI for emscripten.
This is the first fix required for it to build correctly.
This patch defines the FE_INEXACT, FE_INVALID, and related floating-point exception macros when building with Emscripten, since its <fenv.h> header stubs out FE_ALL_EXCEPT but omits the individual FE_* macros.
Check build error here : https://github.com/emscripten-forge/recipes/actions/runs/16363899873/job/46236883737
This was added as a patch on emscripten-forge when 1.0 was released.

Manually define FE_XX macros for emscripten build

---

environment-wasm-host.yml
include/sparrow/config/config.hpp

This should get us started with using sparrow directly with xeus-cpp-lite. We could possibly have an example notebook possibly covering all of sparrow's docs.
Once this goes in and there's a release anytime soon, we could just take a xeus-cpp-lite instance and fetch sparrow through 
`%mamba install sparrow` and put it to use !

Loading sparrow's shared build for emscripten use case
