CMakeLists.txt
environment-dev.yml
include/sparrow/buffer.hpp
test/CMakeLists.txt
test/test_buffer.cpp

Removed sp prefixes

---

include/sparrow/buffer.hpp
test/test_buffer.cpp

Refactored buffer class and added access methods

---

CMakeLists.txt
include/sparrow/array_data.hpp
include/sparrow/data_type.hpp
include/sparrow/dynamic_bitset.hpp

Array data

---

.github/workflows/osx.yml
include/sparrow/buffer.hpp
include/sparrow/dynamic_bitset.hpp

Small PR to add constraints to dynamic bitset types.

Added contraints to dynamic_bitset types

---

include/sparrow/array_data.hpp
test/CMakeLists.txt
test/test_array_data.cpp

Added reference_proxy implementation

---

.github/workflows/linux.yml
.github/workflows/osx.yml
.github/workflows/windows.yml
include/sparrow/layout.hpp

This will catch Debug issues in particular.

CI: setup Debug and Release configurations to run on CI

---

include/sparrow/array_data.hpp
include/sparrow/dynamic_bitset.hpp
include/sparrow/fixed_size_layout.hpp
include/sparrow/iterator.hpp
include/sparrow/variable_size_binary_layout.hpp
test/test_variable_size_binary_layout.cpp

~~Based on #32 , only last commit is relevant.~~

Layout iterator

---

CMakeLists.txt
include/sparrow/allocator.hpp
test/CMakeLists.txt
test/test_allocator.cpp

Implemented type erasure for allocators

---

include/sparrow/buffer_view.hpp
test/test_buffer.cpp

Add buffer_view constructor with iterators and subrange methods

---

CMakeLists.txt
include/sparrow/buffer.hpp
include/sparrow/buffer_adaptor.hpp
test/CMakeLists.txt
test/test_buffer_adaptor.cpp

Add buffer_adaptor

---

include/sparrow/dictionary_encoded_layout.hpp
include/sparrow/fixed_size_layout.hpp
include/sparrow/typed_array.hpp
include/sparrow/variable_size_binary_layout.hpp
test/test_dictionary_encoded_layout.cpp
test/test_fixed_size_layout.cpp
test/test_typed_array.cpp
test/test_variable_size_binary_layout.cpp

Implemented value semantic for typed_array

---

include/sparrow/array/array_data.hpp
include/sparrow/array/array_data_concepts.hpp
include/sparrow/array/array_data_factory.hpp
include/sparrow/array/data_traits.hpp
include/sparrow/layout/dictionary_encoded_layout.hpp
include/sparrow/layout/fixed_size_layout.hpp
include/sparrow/layout/null_layout.hpp
include/sparrow/layout/variable_size_binary_layout.hpp
test/CMakeLists.txt
test/test_array.cpp
test/test_array_data.cpp
test/test_typed_array.cpp

Added Data Storage template parmeter to layout classes

---

CMakeLists.txt
include/sparrow/array/array_data.hpp
include/sparrow/array/array_data_concepts.hpp
include/sparrow/array/array_data_factory.hpp
include/sparrow/array/data_traits.hpp
include/sparrow/array/data_type.hpp
include/sparrow/array/typed_array.hpp
include/sparrow/layout/dictionary_encoded_layout.hpp
include/sparrow/layout/fixed_size_layout.hpp
include/sparrow/layout/layout_iterator.hpp
include/sparrow/layout/null_layout.hpp
include/sparrow/layout/variable_size_binary_layout.hpp
test/test_array_data_concepts.cpp
test/test_array_data_factory.cpp
test/test_traits.cpp

Layout propagation

---

include/sparrow/array/typed_array.hpp
test/test_typed_array.cpp

* construct a typed_array **with fixed layout** with size n and some inital value (#150)
* cleanup

construct from intial value

---

include/sparrow/config/sparrow_version.hpp

Changes version to v0.0.3 so that we can tag this commit.

Release v0.0.3

---

include/sparrow/utils/mp_utils.hpp
test/test_mpl.cpp

Fix mpl::constify

---

.github/workflows/qemu.yaml
CMakeLists.txt
include/sparrow/buffer/buffer.hpp
include/sparrow/buffer/buffer_adaptor.hpp
include/sparrow/buffer/buffer_view.hpp
include/sparrow/layout/fixed_size_layout.hpp
include/sparrow/layout/list_layout/list_layout.hpp
include/sparrow/layout/list_layout/list_layout_value_iterator.hpp
include/sparrow/layout/variable_size_binary_layout.hpp
include/sparrow/utils/bit.hpp
include/sparrow/utils/iterator.hpp
test/CMakeLists.txt
test/test_array_data.cpp
test/test_arrow_array.cpp
test/test_arrow_schema.cpp
test/test_bit.cpp
test/test_buffer_adaptor.cpp
test/test_iterator.cpp

Fix endianess for bigendian archs

---

include/sparrow/arrow_array_schema_proxy.hpp
include/sparrow/arrow_interface/arrow_array_schema_proxy_utils.hpp
test/test_arrow_array_schema_proxy.cpp

The copy semantic is missing but it should be easier to implement it with #206

Arrow proxy

---

CMakeLists.txt
include/sparrow/arrow_array_schema_proxy.hpp
include/sparrow_v01/layout/array_base.hpp
include/sparrow_v01/layout/null_array.hpp
include/sparrow_v01/layout/primitive_array.hpp
test_v01/CMakeLists.txt
test_v01/test_primitive_array.cpp

Implemented primitive_array

---

.github/workflows/linux.yml
include/sparrow/layout/array_base.hpp
include/sparrow/layout/list_layout/list_array.hpp
src/array_factory.cpp
test/external_array_data_creation.cpp
test/external_array_data_creation.hpp
test/test_list_array.cpp

generalized the list layout impl st. all list like layouts (list, list-view, fixed-sized-list) are all implemented with the same core implementation.

list-view,big-list-view and fixed-size-list

---

include/sparrow/layout/array_wrapper.hpp
include/sparrow/utils/memory.hpp
test/test_memory.cpp

This should fix the issue noticed in https://github.com/man-group/sparrow/pull/233

Fixed cloning ptr assignment operator

---

include/sparrow/layout/array_base.hpp
include/sparrow/layout/list_layout/list_array.hpp
include/sparrow/layout/primitive_array.hpp
include/sparrow/layout/struct_layout/struct_array.hpp
include/sparrow/layout/variable_size_binary_array.hpp

I created a common CRTP base class for the bitmap, this will make Alexis' life easier with the mutability PR.
The fix for the copy semantic will come in a dedicated PR.

Moved bitmap instantiation in its own crtp base

---

.github/workflows/windows.yml
CMakeLists.txt
src/dummy32bit.cpp
test/CMakeLists.txt
vcpkg.json

Adds Windows 32bit platforms checks on the CI, but deactivates most of the code for now. We will progressively apply the 32bit fixes.

Windows 32bit CI, only tests dummy code for now

---

include/sparrow/layout/list_layout/list_array.hpp
include/sparrow/layout/run_end_encoded_layout/run_end_encoded_array.hpp
include/sparrow/layout/struct_layout/struct_array.hpp
include/sparrow/layout/union_array.hpp
src/arrow_array_schema_proxy.cpp
test/test_list_array.cpp
test/test_run_end_encoded_array.cpp
test/test_struct_array.cpp
test/test_union_array.cpp

Simplification of arrow_proxy move constructor and move semantic of composed layouts for (almost) free ;)

Move semantic

---

.github/workflows/linux.yml
.github/workflows/osx.yml
.github/workflows/qemu.yaml
.github/workflows/windows.yml
CMakeLists.txt

Thanks the cache, exotics builds are now aroung the minute instead 20 minutes

Add ccache and sccache to the CI

---

include/sparrow/utils/repeat_container.hpp

repeat_view_iterator inherits from sparrow::iterator_base

Improve repeat_container

---

CMakeLists.txt
sparrowConfig.cmake.in

Addresses the comments from https://github.com/apache/iceberg-cpp/pull/44#issuecomment-2646093255

Cmake improvement

---

test/test_time_array.cpp

Fix out-of-bound access in time tests

---

include/sparrow/run_end_encoded_array.hpp

Documentation only, no need to wait for the builds.

Added documentation for run-end encoded array

---

.github/workflows/emscripten.yml
CMakeLists.txt
environment-wasm-build.yml

Currently building with `BUILD_TESTS=OFF`
Shall enable tests through the subsequent PR (#549) once this goes in

Add Emscripten CI
